In [2]:
import geopandas as gpd


# Percorso ai dati dei comuni
comuni_shapefile = 'data/Limiti01012024_g/Com01012024_g/Com01012024_g_WGS84.shp'

comuni = gpd.read_file(comuni_shapefile)

comuni

,COD_RIP,COD_REG,COD_PROV,COD_CM,COD_UTS,PRO_COM,PRO_COM_T,COMUNE,COMUNE_A,CC_UTS,Shape_Leng,Shape_Area,geometry
0,1,1,1,0,201,1001,001001,Agliè,0,0,16075.204018,1.328507e+07,"POLYGON ((404703.561 5026682.656, 405359.557 5..."
1,1,1,1,0,201,1002,001002,Airasca,0,0,16695.878036,1.578186e+07,"POLYGON ((380700.909 4977305.52, 381122.28 497..."
2,1,1,1,0,201,1003,001003,Ala di Stura,0,0,29346.878200,4.576478e+07,"POLYGON ((364710.856 5022090.677, 364737.735 5..."
3,1,1,1,0,201,1004,001004,Albiano d'Ivrea,0,0,16065.852912,1.137642e+07,"POLYGON ((415942.51 5033304.612, 416079.319 50..."
4,1,1,1,0,201,1006,001006,Almese,0,0,16129.778623,1.779612e+07,"POLYGON ((376934.55 4999073.855, 376941.551 49..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7894,5,20,111,0,111,111093,111093,Ussana,0,0,25354.174206,3.280577e+07,"POLYGON ((506682.847 4366573.71, 507215.419 43..."
7895,5,20,111,0,111,111094,111094,Ussaramanna,0,0,14067.831167,9.445897e+06,"POLYGON ((491549.71 4395041.658, 491867.708 43..."
7896,5,20,111,0,111,111095,111095,Vallermosa,0,0,36482.721799,6.167869e+07,"POLYGON ((480817.632 4361907.761, 481929.623 4..."
7897,5,20,111,0,111,111096,111096,Villacidro,0,0,58220.285790,1.832118e+08,"POLYGON ((484374.603 4373966.663, 484094.605 4..."
7898,5,20,111,0,111,111097,111097,Villamar,0,0,28212.773690,3.836818e+07,"POLYGON ((497127.5 4389765.536, 497181.499 438..."

In [3]:
comuni[comuni['PRO_COM_T'] == '001777']

Empty GeoDataFrame
Columns: [COD_RIP, COD_REG, COD_PROV, COD_CM, COD_UTS, PRO_COM, PRO_COM_T, COMUNE, COMUNE_A, CC_UTS, Shape_Leng, Shape_Area, geometry]
Index: []

In [2]:
import pandas as pd

df = pd.read_csv(r"data\input\Attrazioni_culturali.csv")

tab = (df.groupby("tipologia")["numeroLuoghi"]
         .sum()
         .sort_values(ascending=False)
         .to_frame("totale"))

tab

                                                    totale
tipologia
Museo, Galleria e/o raccolta                          4682
Area Archeologica                                      388
Chiesa o edificio di culto                             332
Villa o Palazzo di interesse storico o artistico       186
Altro                                                  175
Architettura Civile                                    175
Monumento                                              156
Archivio di Stato                                      142
Architettura Fortificata                               131
Parco Archeologico                                      81
Parco o Giardino di interesse storico o artistico       63
I tesori della Cultura                                  63
Biblioteca Statale                                      46
Biblioteca                                              34
Monumento Funerario                                     18
Monumento di Archeologia Industriale                    16
Archivio                                                11
Fondazione                                               4
Istituto dotato di autonomia speciale                    3
MiC                                                      2
Comune                                                   2
Soprintendenza Archeologia, Belle Arti e Paesaggio       2
Amministrazione dello Stato                              1
Istituto dotato di autonomia speciale, di rilev...       1
Istituto Centrale                                        1
Regione                                                  1
Soprintendenza Archivistica e Bibliografica              1

In [4]:
from src.utils.cultural_attractions import normalize_name

print(normalize_name("Funes/Villnöß"))

funesvillnoss